name: Allure Report via Docker Compose

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Compose
        run: docker compose version

      - name: Create .env file from GitHub Secrets
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB_AUTH=${{ secrets.POSTGRES_DB_AUTH }}" >> .env
          echo "POSTGRES_DB_UNIVERSITY=${{ secrets.POSTGRES_DB_UNIVERSITY }}" >> .env
          echo "AUTH_SERVICE_INTERNAL_URL=${{ secrets.AUTH_SERVICE_INTERNAL_URL }}" >> .env
          echo "AUTH_SERVICE_API_URL=${{ secrets.AUTH_SERVICE_API_URL }}" >> .env
          echo "UNIVERSITY_SERVICE_INTERNAL_URL=${{ secrets.UNIVERSITY_SERVICE_INTERNAL_URL }}" >> .env
          echo "UNIVERSITY_SERVICE_API_URL=${{ secrets.UNIVERSITY_SERVICE_API_URL }}" >> .env
          echo "API_USERNAME=${{ secrets.API_USERNAME }}" >> .env
          echo "API_PASSWORD=${{ secrets.API_PASSWORD }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          

      - name: Build and run tests
        run: |
          docker compose down || true
          docker compose up --build --abort-on-container-exit || true

      - name: Copy Allure report from container
        run: |
          mkdir -p allure-report
          docker cp test-framework:/tests/allure-report ./allure-report || echo "No report found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
